#a,o(+,-,*,/,//,**)
num1=int(input("Enter value for num1"))
num2=int(input("Enter value for num2"))
addresult=int(num1+num2)
mulresult=int(num1*num2)
divresult=(num1/num2)
modresult=int(num1%num2)
doubledivresult=(num1//num2)
powerresult=int(num1**num2)
sub=num1-num2
print("addition Result=",addresult)
print("multiplicationResult=",mulresult)
print("division Result=",divresult)
print("mod Result=",modresult)
print("DoubledivisionResult=",doubledivresult)
print("Pow Result=",powerresult)
print("SuB Result=",sub)
